# Generated by Django 6.0 on 2026-01-22 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carmodel_car_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('gas', 'Gas')], default='electric', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
