# Generated by Django 6.0 on 2025-12-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_cars', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
