# Generated by Django 6.0 on 2025-12-30 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carmodel_created_at_carmodel_updated_at'),
        ('car_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_shop.carshopmodel'),
            preserve_default=False,
        ),
    ]
